backend:
  name: github
  repo: utili-site/malisauskas
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  [
    {
      name: pages,
      label: Pages,
      create: true,
      files:
        [
          {
            label: Home,
            name: home,
            file: "content/home.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Thumbnail Image", name: thumbnail, widget: image },
                { label: "Featured Image", name: featured, widget: image },
                { label: "More URL", name: url, widget: string },
                { label: "More label", name: more, widget: string },
                {
                  label: Tags,
                  name: tags,
                  widget: list,
                  field: { label: Tag, name: tag, widget: string },
                },
              ],
          },
          {
            label: Porfolio,
            name: portfolio,
            file: "content/portfolio.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Thumbnail Image", name: thumbnail, widget: image },
                { label: "Featured Image", name: featured, widget: image },
                { label: "More URL", name: url, widget: string },
                { label: "More label", name: more, widget: string },
                {
                  label: Tags,
                  name: tags,
                  widget: list,
                  field: { label: Tag, name: tag, widget: string },
                },
              ],
          },
          {
            label: Services,
            name: servies,
            file: "content/services.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Thumbnail Image", name: thumbnail, widget: image },
                { label: "Featured Image", name: featured, widget: image },
                { label: "More URL", name: url, widget: string },
                { label: "More label", name: more, widget: string },
                {
                  label: Tags,
                  name: tags,
                  widget: list,
                  field: { label: Tag, name: tag, widget: string },
                },
              ],
          },
          {
            label: Clients,
            name: clients,
            file: "content/clients.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Thumbnail Image", name: thumbnail, widget: image },
                { label: "Featured Image", name: featured, widget: image },
                { label: "More URL", name: url, widget: string },
                { label: "More label", name: more, widget: string },
                {
                  label: Tags,
                  name: tags,
                  widget: list,
                  field: { label: Tag, name: tag, widget: string },
                },
              ],
          },
        ],
    },
    {
      name: portfolio,
      label: Portfolio,
      folder: portfolio,
      create: true,
      slug: "{{slug}}",
      fields:
        [
          { label: Title, name: title, widget: string },
          { label: Body, name: body, widget: markdown },
          { label: "Thumbnail Image", name: thumbnail, widget: image },
          { label: "Featured Image", name: featured, widget: image },
          { label: "More URL", name: url, widget: string },
          { label: "More label", name: more, widget: string },
          {
            label: Tags,
            name: tags,
            widget: list,
            field: { label: Tag, name: tag, widget: string },
          },
        ],
    },
    {
      name: clients,
      label: Clients,
      folder: clients,
      create: true,
      slug: "{{slug}}",
      fields:
        [
          { label: Title, name: title, widget: string },
          { label: Logo, name: logo, widget: image },
          { label: Body, name: body, widget: "text" },
          { label: URL, name: url, widget: string },
        ],
    },
  ]
