backend:
  name: github
  repo: utili-site/malisauskas
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  [
    {
      name: pages,
      label: Pages,
      create: false,
      files:
        [
          {
            label: Home,
            name: home,
            file: "content/home.md",
            fields:
              [
                { label: "Hero Prefix", name: hero_prefix, widget: string },
                {
                  label: "Hero Variants",
                  name: hero_variants,
                  widget: list,
                  field: { label: Variant, name: variant, widget: string },
                },
                { label: "Hero Suffix", name: hero_suffix, widget: string },
              ],
          },
          {
            label: Porfolio,
            name: portfolio,
            file: "content/portfolio.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, minimal: true, widget: markdown, required: false },
                {
                  label: Blocks,
                  name: blocks,
                  widget: list,
                  summary: "{{block}}",
                  field:
                    {
                      label: Block,
                      name: block,
                      widget: relation,
                      required: false,
                      collection: works,
                      value_field: title,
                      search_fields: ["title", "body"],
                    },
                },
              ],
          },
          {
            label: Services,
            name: servies,
            file: "content/services.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, minimal: true, widget: markdown },
                { label: "Thumbnail Image", name: thumbnail, widget: image },
                { label: "Featured Image", name: featured, widget: image },
                { label: "More URL", name: url, widget: string },
                { label: "More label", name: more, widget: string },
                { label: Tags, name: tags, widget: list, field: { label: Tag, name: tag, widget: string } },
              ],
          },
          {
            label: Clients,
            name: clients,
            file: "content/clients.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, minimal: true, widget: markdown },
                {
                  label: Clients,
                  name: items,
                  widget: list,
                  summary: "{{fields.title}}",
                  fields:
                    [
                      { label: Titlte, name: title, widget: string },
                      { label: Logo, name: logo, widget: image },
                      { label: Body, name: body, widget: "text" },
                      { label: URL, name: url, widget: string },
                    ],
                },
              ],
          },
        ],
    },
    {
      name: works,
      label: Works,
      folder: "content/works",
      create: true,
      slug: "{{slug}}",
      fields:
        [
          { label: Title, name: title, widget: string },
          { label: Body, name: body, minimal: true, widget: markdown, required: false },
          { label: "Thumbnail Image", name: thumbnail, widget: image, required: false },
          { label: "Featured Image", name: featured, widget: image, required: false },
          { label: "More URL", name: url, widget: string, required: false },
          { label: "More label", name: more, widget: string, required: false },
          { label: Tags, name: tags, widget: list, field: { label: Tag, name: tag, widget: string } },
        ],
    },
    {
      name: ui,
      label: UI,
      create: false,
      files:
        [
          {
            label: Header,
            name: header,
            file: "content/ui/header.md",
            fields:
              [
                { label: Phone, name: phone, widget: string, required: false },
                { label: Email, name: email, widget: string, required: false },
                { label: "Let's talk", name: talk, widget: string },
                {
                  label: Navigation,
                  name: nav,
                  widget: list,
                  summary: "{{block}}",
                  fields:
                    [
                      { label: Label, name: label, widget: string },
                      {
                        label: Page,
                        name: page,
                        widget: relation,
                        collection: pages,
                        value_field: title,
                        search_fields: ["title", "body"],
                      },
                    ],
                },
              ],
          },
        ],
    },
  ]
