backend:
  name: github
  repo: utili-site/malisauskas
  branch: dev
  # branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  [
    {
      name: pages,
      label: Pages,
      create: false,
      files:
        [
          {
            label: Home,
            name: home,
            file: "content/home.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: "Left Color", name: leftBlobColor, widget: color },
                { label: "Right Color", name: rightBlobColor, widget: color },
                { label: "Hero Prefix", name: hero_prefix, widget: string },
                {
                  label: "Hero Variants",
                  name: hero_variants,
                  widget: list,
                  field: { label: Variant, name: variant, widget: string },
                },
                { label: "Hero Suffix", name: hero_suffix, widget: string },
                { label: "Hero Clients Intro", name: hero_clients_intro, widget: text  },
                { label: "Services Title", name: flow_title, widget: string },
                { label: "Services Intro", name: flow_intro, widget: markdown },
                { label: "Services Year Label", name: flow_year_label, widget: string },
                { label: "Services Year Value", name: flow_year_value, widget: string },
                { label: "Services CTA", name: flow_cta, widget: string },
                { label: "Portfolio Title", name: showcase_title, widget: string },
                { label: "Portfolio Intro", name: showcase_intro, widget: markdown },
                {
                  label: "Portfolio Blocks",
                  name: showcase_blocks,
                  widget: list,
                  summary: "{{block}}",
                  field:
                    {
                      label: Block,
                      name: block,
                      widget: relation,
                      required: false,
                      collection: works,
                      value_field: title,
                      search_fields: ["title", "body"],
                    },
                },
                { label: "Portfolio See All", name: showcase_all, widget: string },
                {
                  label: "Feedback Blocks",
                  name: feedback,
                  widget: list,
                  summary: "{{fields.name}}",
                  fields:
                    [
                      { label: Text, name: text, widget: text },
                      { label: Name, name: name, widget: string },
                      { label: Position, name: position, widget: string },
                    ],
                },
              ],
          },
          {
            label: Porfolio,
            name: portfolio,
            file: "content/portfolio.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, minimal: true, widget: markdown, required: false },
                { label: "Left Color", name: leftBlobColor, widget: color },
                { label: "Right Color", name: rightBlobColor, widget: color },
                {
                  label: Blocks,
                  name: blocks,
                  widget: list,
                  summary: "{{block}}",
                  field:
                    {
                      label: Block,
                      name: block,
                      widget: relation,
                      required: false,
                      collection: works,
                      value_field: title,
                      search_fields: ["title", "body"],
                    },
                },
              ],
          },
          {
            label: Services,
            name: services,
            file: "content/services.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, minimal: true, widget: markdown },
                { label: "Left Color", name: leftBlobColor, widget: color },
                { label: "Right Color", name: rightBlobColor, widget: color },
                { label: "Services Color", name: servicesBlobColor, widget: color },
                { label: Years, name: years, widget: string },
                { label: Experience, name: experience, widget: string },
                {
                  label: Steps,
                  name: steps,
                  widget: list,
                  summary: "{{fields.title}}",
                  fields:
                    [
                      { label: Title, name: title, widget: string },
                      { label: Body, name: body, widget: text },
                    ],
                },
                {
                  label: Services,
                  name: blocks,
                  widget: list,
                  summary: "{{fields.title}}",
                  fields:
                    [
                      { label: Title, name: title, widget: string },
                      { label: Body, name: body, widget: text },
                      { label: Background, name: background, widget: image },
                    ],
                },
                { label: Subtitle, name: subtitle, widget: string },
                { label: CTA, name: cta, widget: string },
              ],
          },
          {
            label: Clients,
            name: clients,
            file: "content/clients.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, minimal: true, widget: markdown },
                { label: "Left Color", name: leftBlobColor, widget: color },
                { label: "Right Color", name: rightBlobColor, widget: color },
                {
                  label: Clients,
                  name: items,
                  widget: list,
                  summary: "{{fields.body}}",
                  fields:
                    [
                      { label: Logo, name: logo, widget: image },
                      { label: Body, name: body, widget: "text" },
                    ],
                },
              ],
          },
        ],
    },
    {
      name: works,
      label: Works,
      folder: "content/works",
      create: true,
      slug: "{{slug}}",
      fields:
        [
          { label: Title, name: title, widget: string },
          { label: Body, name: body, minimal: true, widget: markdown, required: false },
          { label: "Thumbnail Image", name: thumbnail, widget: image, required: false },
          { label: "Featured Image", name: featured, widget: image, required: false },
          { label: "More URL", name: url, widget: string, required: false },
          { label: "More label", name: more, widget: string, required: false },
          { label: Tags, name: tags, widget: list, field: { label: Tag, name: tag, widget: string } },
        ],
    },
    {
      name: ui,
      label: UI,
      create: false,
      files:
        [
          {
            label: Header,
            name: header,
            file: "content/ui/header.md",
            fields:
              [
                { label: Phone, name: phone, widget: string, required: false },
                { label: Email, name: email, widget: string, required: false },
                { label: "Let's talk", name: talk, widget: string },
                { label: Navigation, name: nav, widget: list, summary: "{{fields.label}}", fields: [
                      { label: Label, name: label, widget: string },
                      {
                        label: Page,
                        name: page,
                        widget: relation,
                        collection: pages,
                        value_field: "{{slug}}",
                        display_fields: [title],
                        search_fields: [title, body],
                      },
                    ] },
              ],
          },
          {
            label: Footer,
            name: footer,
            file: "content/ui/footer.md",
            fields:
              [
                { label: Footnote, name: footnote, widget: string, required: false },
                {
                  label: "Social links",
                  name: socials,
                  widget: list,
                  summary: "{{fields.label}}",
                  fields:
                    [
                      { label: Label, name: label, widget: string },
                      { label: URL, name: url, widget: string },
                      { label: Icon, name: icon, widget: image },
                    ],
                },
              ],
          },
        ],
    },
  ]
