backend:
  name: github
  repo: utili-site/malisauskas
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  [
    {
      name: pages,
      label: Pages,
      create: true,
      files:
        [
          {
            label: Home,
            name: home,
            file: "content/home.md",
            fields:
              [
                { label: "Hero Prefix", name: hero_prefix, widget: string },
                {
                  label: "Hero Variants",
                  name: hero_variants,
                  widget: list,
                  field: { label: Variant, name: variant, widget: string },
                },
                { label: "Hero Suffix", name: hero_suffix, widget: string },
              ],
          },
          {
            label: Porfolio,
            name: portfolio,
            file: "content/portfolio.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown, required: false },
                {
                  label: Tags,
                  name: tags,
                  widget: list,
                  required: false,
                  field: { label: Tag, name: tag, widget: string },
                },
              ],
          },
          {
            label: Services,
            name: servies,
            file: "content/services.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                { label: "Thumbnail Image", name: thumbnail, widget: image },
                { label: "Featured Image", name: featured, widget: image },
                { label: "More URL", name: url, widget: string },
                { label: "More label", name: more, widget: string },
                {
                  label: Tags,
                  name: tags,
                  widget: list,
                  field: { label: Tag, name: tag, widget: string },
                },
              ],
          },
          {
            label: Clients,
            name: clients,
            file: "content/clients.md",
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Body, name: body, widget: markdown },
                {
                  label: Clients,
                  name: items,
                  widget: list,
                  fields:
                    [
                      { label: Logo, name: logo, widget: image },
                      { label: Body, name: body, widget: "text" },
                      { label: URL, name: url, widget: string },
                    ],
                },
              ],
          },
        ],
    },
    {
      name: portfolio,
      label: Portfolio,
      folder: "conent/portfolio",
      create: true,
      slug: "{{slug}}",
      fields:
        [
          { label: Title, name: title, widget: string },
          { label: Body, name: body, widget: markdown, required: false },
          {
            label: "Thumbnail Image",
            name: thumbnail,
            widget: image,
            required: false,
          },
          {
            label: "Featured Image",
            name: featured,
            widget: image,
            required: false,
          },
          { label: "More URL", name: url, widget: string, required: false },
          { label: "More label", name: more, widget: string, required: false },
          {
            label: Tags,
            name: tags,
            widget: list,
            field: { label: Tag, name: tag, widget: string },
          },
        ],
    },
    {
      name: clients,
      label: Clients,
      folder: clients,
      create: true,
      slug: "{{slug}}",
      fields:
        [
          { label: Title, name: title, widget: string },
          { label: Logo, name: logo, widget: image },
          { label: Body, name: body, widget: "text" },
          { label: URL, name: url, widget: string },
        ],
    },
  ]
